### ISSUE TITLE
RAW package on powershellgallery wrong version

### ISSUE THREAD

**Issue by ivoruetsche** [PKISolutions/PSPKI#84]
Hi

The "Manually download the .nupkg file" have a wrong directory version in the package. The file PSPKI.psd1 is pointed to "ModuleVersion = '3.4.1.0'", but the directory in the nuget package is 3.4.1 - so I can't import the module.

"https://psg-prod-eastus.azureedge.net/packages/pspki.3.4.1.nupkg"

Ivo

**Comment by Crypt32** [comment]
fixed with new release: https://www.powershellgallery.com/packages/PSPKI/3.4.2.0

**Comment by ivoruetsche** [comment]
Hi

There is still a problem with the version:


We have our own Repo:
```
PS C:\Program Files\WindowsPowerShell\Modules> Get-PSRepository

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
ourinfraPowerShellRepo     Trusted              \\ourinfra\myn-ourinfra\install\PowerShellRepo
```

The package is there:
```
PS C:\Program Files\WindowsPowerShell\Modules>dir \\ourinfra\myn-ourinfra\install\PowerShellRepo\pspki*


    Directory: \\ourinfra\myn-ourinfra\install\PowerShellRepo


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       29.08.2019     15:31        1360151 pspki.3.4.2.nupkg
```

Now, package installation works:
```
PS C:\Program Files\WindowsPowerShell\Modules> Install-Package PSPKI
WARNING: MSG:UnableToDownload «https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409» «»
WARNING: Unable to download the list of available providers. Check your internet connection.

Name                           Version          Source           Summary
----                           -------          ------           -------
PSPKI                          3.4.2            ourinfraPowerS... This module contains public key infrastructure and certificate management functions. Support site: https://www.pkisolutions.com/tools/p...
```

But the module import does not:
```
PS C:\Program Files\WindowsPowerShell\Modules> Import-module -Name PSPKI -Prefix PSPKI
Import-module : The specified module 'PSPKI' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-module -Name PSPKI -Prefix PSPKI
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (PSPKI:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

Let's change the Version in the psd1 file:
```
PS C:\Program Files\WindowsPowerShell\Modules> Get-Content .\PSPKI\3.4.2\PSPKI.psd1 | findstr -I -N ModuleVersion
7:    ModuleVersion = '3.4.2.0'
PS C:\Program Files\WindowsPowerShell\Modules> (Get-Content .\PSPKI\3.4.2\PSPKI.psd1).replace('3.4.2.0', '3.4.2') | Set-Content .\PSPKI\3.4.2\PSPKI.psd1
PS C:\Program Files\WindowsPowerShell\Modules> Get-Content .\PSPKI\3.4.2\PSPKI.psd1 | findstr -I -N ModuleVersion
7:    ModuleVersion = '3.4.2'
```

Now, the import works:
```
PS C:\Program Files\WindowsPowerShell\Modules> Import-module -Name PSPKI -Prefix PSPKI
PS C:\Program Files\WindowsPowerShell\Modules> Get-module -Name PSPKI

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.4.2      PSPKI                               {Add-PSPKIAdCertificate, Add-PSPKIAdCertificateRevocationList, Add-PSPKIAuthorityInformationAccess, Add-PSPKICAAccessControlEntry...}
```

So, in the .psd1 file should be 3.4.2, not 3.4.2.0

gruss ivo
